export AWS_ACCESS_KEY_ID='AAAAAAAAAAAAAAAAAA'
export AWS_SECRET_ACCESS_KEY='BBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
export AWS_REGION='us-west-2'
export ANSIBLE_HOSTS=/etc/ansible/ec2.py
export EC2_INI_PATH=/etc/ansible/ec2.ini 

