---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning

    vars:
      instance_type: t2.micro
      security_group: tomcat-sesrver 
      image: ami-4dbf9e7d
      region: us-west-2
      keypair: mk-keypair
      count: 2 

    tasks:

      - name: Create a security group
        local_action:
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group
          region: "{{ region }}"
          rules:
            - proto: tcp
              type: ssh
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 9000
              to_port: 9000
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              type: all
              cidr_ip: 0.0.0.0/0

      - name: Launch the new EC2 Instance
        local_action: ec2
                      instance_tags="Name=demo"
                      group={{ security_group }}
                      instance_type={{ instance_type}}
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2

      - name: Add the new EC2 instance(s) to Ansible hosts group
        local_action: lineinfile
                      dest="/etc/ansible/hosts"
                      regexp={{ item.public_ip }}
                      insertafter="[demo-servers]" line={{ item.public_ip }}
        with_items: ec2.instances

      - name: Wait for the provisioned server is up
        local_action: wait_for
                      host={{ item.public_ip }}
                      port=22
                      state=started
        with_items: ec2.instances

